[package]
authors = ["Jake O'Shannessy <joshannessy@smokecloud.com>"]
edition = "2021"
name = "fdspp"
version = "0.2.4"

[dependencies]
clap = { version = "4", features = ["cargo"] }
namelist = {git = "https://github.com/Smoke-Cloud/namelist-rs.git", branch = "new-parser"}
